# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Copilot Setup Steps

# This workflow is triggered by GitHub Copilot to set up the development environment
# for coding agents to build, lint, and test the repository.

on: workflow_dispatch

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Set up Rust nightly
        uses: dtolnay/rust-toolchain@nightly

      - name: Setup environment
        run: just setup

      - name: Run code quality checks
        run: just check
